server:
  port: 8080
spring:
  application:
    name: flow-server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
# mybatis config
mybatis:
  mapper-locations: classpath:/mapper/*.xml
# logging
logging:
  config: classpath:logback-spring.xml
  path: D:/app/logs/
# eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/
#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql